lab3/urls.py
from django.urls import path
from . import views

app_name = "lab3"
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('admin', views.admin, name='admin'),
    path('details', views.details, name='details'),
    path('credentials', views.credentials, name='credentials'),
    path('search', views.search, name='search'),
    path('succeed', views.succeed, name='succeed'),
]

vulnerableapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.views.static import serve
from django.urls import re_path as url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('lab3.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

lab3/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username= models.CharField(max_length=100,unique=True)
    password= models.CharField(max_length=100)
    cc= models.CharField(max_length=19,default='', blank=True)
    def __str__(self):
        return self.username

lab3/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
import os
from django.db import connection
from .models import User
import js2py

# Create your views here.
def index(request):
    if request.method == 'POST':
        del request.session['username']
        return render(request, 'index.html', {"username" : ""})
    else:
        if request.session.has_key('username'):
            username = request.session['username']
            return render(request,  'index.html', {"username" : username})
        else:
            return render(request, 'index.html', {"username" : ""})

def details(request):
    if request.method == 'POST':
        del request.session['username']
        return render(request, 'index.html', {"username" : ""})
    if request.GET.get("pass") is not None:
        User.objects.filter(username=request.GET.get("user")).update(password=request.GET.get("pass"))
        user = request.session['username']
        name = User.objects.filter(username=user)[0].username
        passw = User.objects.filter(username=user)[0].password
        return render(request,  'details.html', {"name" : name, "pass": passw, "username" : user})
    user = request.session['username']
    name = User.objects.filter(username=user)[0].username
    passw = User.objects.filter(username=user)[0].password
    return render(request,  'details.html', {"name" : name, "pass": passw, "username" : user})

def login(request):
    args = {}
    if request.method == 'POST':
        try:
            mycorrectpass = User.objects.filter(username=request.POST.get("user"))[0].password
        except:
            args = {}
            args['message'] = "Unknown Username!"
            return render(request, 'login.html',args)
        result, tempfile = js2py.run_file("md5.js");
        result= tempfile.encrypt(mycorrectpass);
        if result == request.POST.get("pass"):
            request.session['username'] = request.POST.get("user")
            if request.POST.get("user") == "admin":
                return redirect('lab3:admin')
            else:
                return redirect('lab3:index')
        else:
            args = {}
            args['message'] = "Wrong Credentials!"
            return render(request, 'login.html',args)

    else:
        return render(request, 'login.html')

def admin(request):
    if request.method == 'POST':
        param = request.POST.get('path')
        startdir = os.path.abspath(os.curdir)
        requested_path = os.path.relpath(param, startdir)
        requested_path = os.path.abspath(requested_path)
        tfile = open(requested_path, 'rb')
        response = HttpResponse(content=tfile, content_type="text/html")
        response['Content-Disposition'] = "attachment; filename=usercredentials.html"
        return response
    else:
        return render(request, 'admin.html')

def credentials(request):
    if request.method == 'POST':
        User.objects.filter(username=request.session['username']).update(cc=request.POST.get("cc"))
        return render(request, 'succeed.html')
    else:
        return render(request, 'credentials.html')

def succeed(request):
    return render(request, 'succeed.html')

def register(request):
    if request.method == 'POST':
        try:
            if request.POST.get("user") == "" or request.POST.get("pass") == "":
                args = {}
                args['message'] = "Please fill in your data!"
                return render(request, 'register.html',args)
            User.objects.create(username = request.POST.get("user"), password = request.POST.get("pass"))
        except:
            args = {}
            args['message'] = "Try another Username!"
            return render(request, 'register.html',args)
        return redirect('lab3:login')

    return render(request, 'register.html')

def search(request):
    if request.session.has_key('username'):
            username = request.session['username']
    if request.method == 'POST':
        if request.POST.get("usersearch") is not None:
            cursor = connection.cursor()
            query = "SELECT id, username FROM lab3_user WHERE username = '" + str(request.POST.get("usersearch")) +"'"
            users = cursor.execute(query)
            return render(request, 'search.html', {"username" : username, "users" : users , "searched": request.POST.get("usersearch")})
        del request.session['username']
        return render(request, 'index.html', {"username" : ""})
    return render(request, 'search.html', {"username" : username, "searched": ""})

templates/admin.html

<style>
html {
  background-color: #565656
}

body {
  font-size: 18px;
  font-family: Verdana, Geneva, sans-serif;
  line-height: 1.5;
  color: white;
}

.navbar {
  height: 50px;
  position: fixed;
  width: 100%;
  background-image: linear-gradient(#081829 , #6B798C);
  z-index: 100;
}

.wrapper, .main-wrapper {
  width: 1200px;
  margin: 0 auto;
  padding-left: 30px;
  padding-right: 30px;
  box-sizing: border-box;

}

.navbar .wrapper {
  background-color: rgba(255,255,255,0.1);
}

.main-wrapper {
  font-size: 1.1em;
  padding-top: 80px;
  padding-bottom: 80px;
  padding-right: 80px;
  padding-left: 80px;
  background-image:  url("https://i.imgur.com/VGv0QE1.jpg");
  background-size: cover;
  position: relative;
  z-index: 1;
}

.logo {
  display: inline-block;
}

.logo a {
  line-height: 50px;
  font-size: 1.75em;
  font-weight: bold;
  text-decoration: none;
  color: gold;
}

.mainmenu {
  float: right;
  list-style: none;
  padding: 0;
  margin: 0;
  font-size: 0;
}

.mainmenu li {
  display: inline;
}

.mainmenu li a {
  line-height: 50px;
  text-decoration: none;
  color: black;
  font-size: 18px;
  font-weight: bold;
}

.mainmenu li a:hover {
  color: #EDA444;
}

.mainmenu li:not(:last-child) {
  margin-right: 30px;
}

img.myface {
  float: left;
  border-radius: 10px;
  margin-right: 30px;
}

.section:before {
  content: " ";
  display: block;
  position: absolute;
  width: 100%;
  height: 100%;
  background-color: rgba(11,66,131,0.5);
  left: 0px;
  top: 0px;
  z-index: -1;
  border-radius: 10px;
}



.section {
  z-index: 100;
  position: relative;
  padding: 30px;
  vertical-align: top;
  
}

.section h1 {
  margin: 0;
}

.section p {
  position: relative;
}

.section a{
  color: gold;
  font-weight: bold;
  text-decoration: none;
}

.section a:hover {
  color: red;
}

img.ninetysdesk {
  border-radius: 10px;
  margin-left: 30px;
  float: right;
}

img.webtech {
  border-radius: 10px;
  margin-right: 30px;
  float: left;
}

img {
  box-shadow: 2px 2px 3px 0px rgba(0,0,0,0.8);
  background-color: white;
}

td {
  padding: 10px;
  vertical-align: bottom;
}

table {
  float: left;
}

.clearfix {
  clear: both;
  height: 0px;
}
</style>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<nav class="navbar">
    <div class="wrapper">
      <div class="logo"><a href="{% url 'lab3:index' %}">Security Lab</a></div>
      <ul class="mainmenu">
        </ul>
      </div>
    </nav>
    
    <div class="main-wrapper">
     <div class="section about-section">
      <h1>Welcome admin</h1>
      <p>This is a restricted page.</p>
      <form method = "post">
        {% csrf_token %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <a href = "{% url 'lab3:admin' %}" download="User Credentials">
        <!--Mitigation: Remove input option and make it hardcoded in backend-->
        <input type = "hidden" name = "path" value = "usercredentials.html">
        <button class="btn"><i class="fa fa-download"></i>User Credentials</button></a>
      </form>
     </div>
    </div>
</html>

templates/credentials.html

<style>
    html {
      background-color: #565656
    }
    
    body {
      font-size: 18px;
      font-family: Verdana, Geneva, sans-serif;
      line-height: 1.5;
      color: white;
    }
    
    .navbar {
      height: 50px;
      position: fixed;
      width: 100%;
      background-image: linear-gradient(#081829 , #6B798C);
      z-index: 100;
    }
    
    .wrapper, .main-wrapper {
      width: 1200px;
      margin: 0 auto;
      padding-left: 30px;
      padding-right: 30px;
      box-sizing: border-box;
    
    }
    
    .navbar .wrapper {
      background-color: rgba(255,255,255,0.1);
    }
    
    .main-wrapper {
      font-size: 1.1em;
      padding-top: 80px;
      padding-bottom: 80px;
      padding-right: 80px;
      padding-left: 80px;
      background-image:  url("https://i.imgur.com/VGv0QE1.jpg");
      background-size: cover;
      position: relative;
      z-index: 1;
    }
    
    .logo {
      display: inline-block;
    }
    
    .logo a {
      line-height: 50px;
      font-size: 1.75em;
      font-weight: bold;
      text-decoration: none;
      color: gold;
    }
    
    .mainmenu {
      float: right;
      list-style: none;
      padding: 0;
      margin: 0;
      font-size: 0;
    }
    
    .mainmenu li {
      display: inline;
    }
    
    button{
      line-height: 50px;
      text-decoration: none;
      color: black;
      font-size: 18px;
      font-weight: bold;
      padding: 0;
      border: none;
      background: none;
    }
    
    button:hover{
      color: #EDA444;
    }
    
    .mainmenu li a{
      line-height: 50px;
      text-decoration: none;
      color: black;
      font-size: 18px;
      font-weight: bold;
    }
    
    .mainmenu li a:hover {
      color: #EDA444;
    }
    
    .mainmenu li:not(:last-child) {
      margin-right: 30px;
    }
    
    img.myface {
      float: left;
      border-radius: 10px;
      margin-right: 30px;
    }
    
    .section:before {
      content: " ";
      display: block;
      position: absolute;
      width: 100%;
      height: 100%;
      background-color: rgba(11,66,131,0.5);
      left: 0px;
      top: 0px;
      z-index: -1;
      border-radius: 10px;
    }
    
    
    
    .section {
      z-index: 100;
      position: relative;
      padding: 30px;
      vertical-align: top;
      
    }
    
    .section h1 {
      margin: 0;
    }
    
    .section p {
      position: relative;
    }
    
    .section a{
      color: gold;
      font-weight: bold;
      text-decoration: none;
    }
    
    .section a:hover {
      color: red;
    }
    
    img.ninetysdesk {
      border-radius: 10px;
      margin-left: 30px;
      float: right;
    }
    
    img.webtech {
      border-radius: 10px;
      margin-right: 30px;
      float: left;
    }
    
    img {
      box-shadow: 2px 2px 3px 0px rgba(0,0,0,0.8);
      background-color: white;
    }
    
    td {
      padding: 10px;
      vertical-align: bottom;
    }
    
    table {
      float: left;
    }
    
    .clearfix {
      clear: both;
      height: 0px;
    }
    </style>
    <html>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <nav class="navbar">
        <div class="wrapper">
            <div class="logo"><a href="{% url 'lab3:index' %}">Security Lab</a></div>
            <ul class="mainmenu">
            </ul>
          </div>
        </nav>
        <div class="main-wrapper">
         <div class="section about-section">
            <h1>Enter Credit Card</h1>
            <form method="post">
              {% csrf_token %}
              <input id="password" name="cc" placeholder="XXXX-XXXX-XXXX-XXXX" />
              <button type="submit"  onclick="encrypt()">Submit</button>
            </form>
         </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/aes.js"></script>
        <script>
        function encrypt() {
            var key = CryptoJS.enc.Hex.parse("000102030405060708090a0b0c0d0e0f");
            var iv = CryptoJS.enc.Hex.parse("101112131415161718191a1b1c1d1e1f");
            var plain = document.getElementById("password").value;
            var encrypted = CryptoJS.AES.encrypt(plain, key, { iv: iv });
            document.getElementById("password").value = encrypted;
        }
        </script>
    </html>

templates/details.html

<style>
html {
  background-color: #565656
}

body {
  font-size: 18px;
  font-family: Verdana, Geneva, sans-serif;
  line-height: 1.5;
  color: white;
}

.navbar {
  height: 50px;
  position: fixed;
  width: 100%;
  background-image: linear-gradient(#081829 , #6B798C);
  z-index: 100;
}

.wrapper, .main-wrapper {
  width: 1200px;
  margin: 0 auto;
  padding-left: 30px;
  padding-right: 30px;
  box-sizing: border-box;

}

.navbar .wrapper {
  background-color: rgba(255,255,255,0.1);
}

.main-wrapper {
  font-size: 1.1em;
  padding-top: 80px;
  padding-bottom: 80px;
  padding-right: 80px;
  padding-left: 80px;
  background-image:  url("https://i.imgur.com/VGv0QE1.jpg");
  background-size: cover;
  position: relative;
  z-index: 1;
}

.logo {
  display: inline-block;
}

.logo a {
  line-height: 50px;
  font-size: 1.75em;
  font-weight: bold;
  text-decoration: none;
  color: gold;
}

.mainmenu {
  float: right;
  list-style: none;
  padding: 0;
  margin: 0;
  font-size: 0;
}

.mainmenu li {
  display: inline;
}

button{
  line-height: 50px;
  text-decoration: none;
  color: black;
  font-size: 18px;
  font-weight: bold;
  padding: 0;
  border: none;
  background: none;
}

button:hover{
  color: #EDA444;
}

.mainmenu li a{
  line-height: 50px;
  text-decoration: none;
  color: black;
  font-size: 18px;
  font-weight: bold;
}

.mainmenu li a:hover {
  color: #EDA444;
}

.mainmenu li:not(:last-child) {
  margin-right: 30px;
}

img.myface {
  float: left;
  border-radius: 10px;
  margin-right: 30px;
}

.section:before {
  content: " ";
  display: block;
  position: absolute;
  width: 100%;
  height: 100%;
  background-color: rgba(11,66,131,0.5);
  left: 0px;
  top: 0px;
  z-index: -1;
  border-radius: 10px;
}



.section {
  z-index: 100;
  position: relative;
  padding: 30px;
  vertical-align: top;
  
}

.section h1 {
  margin: 0;
}

.section p {
  position: relative;
}

.section a{
  color: gold;
  font-weight: bold;
  text-decoration: none;
}

.section a:hover {
  color: red;
}

img.ninetysdesk {
  border-radius: 10px;
  margin-left: 30px;
  float: right;
}

img.webtech {
  border-radius: 10px;
  margin-right: 30px;
  float: left;
}

img {
  box-shadow: 2px 2px 3px 0px rgba(0,0,0,0.8);
  background-color: white;
}

td {
  padding: 10px;
  vertical-align: bottom;
}

table {
  float: left;
}

.clearfix {
  clear: both;
  height: 0px;
}
</style>
<html>
{% autoescape off %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<nav class="navbar">
  <div class="wrapper">
    <div class="logo"><a href="{% url 'lab3:index' %}">Security Lab</a></div>
    <ul class="mainmenu">
      <form method="post">
        {% csrf_token %}
      {% if username != "" %}
      <li><a href="{% url 'lab3:details' %}">Welcome {{username}}</a></li>
      <li><a href="{% url 'lab3:search' %}">Search Users</a></li>
      <button type="submit">Log Out</button>
      {% endif %}
      </form>
      {% if username == "" %}
      <li><a href="{% url 'lab3:register' %}">Register</a></li>
      <li><a href="{% url 'lab3:login' %}">Login</a></li>
      {% endif %}
    </ul>
  </div>
    </nav>
    
    <div class="main-wrapper">
     <div class="section about-section">
      <h1>User Details</h1>
       <h3>Username</h3>
       <p>{{name}}</p>
       <h3>Password</h3>
       <p>{{pass}}</p>
       
      <div class="change-password">
        <h1>Change Password</h1>
        <form method="get">
          {% csrf_token %}
          <input type="hidden" name = "user" value="{{name}}"/>
          <input type="password" name="pass" placeholder="new password"/>
          <button type="submit">Change Password</button>
        </form>
      </div>
     </div>
    </div>
{% endautoescape %}
    
</html>

templates/index.html

<style>
html {
  background-color: #565656
}

body {
  font-size: 18px;
  font-family: Verdana, Geneva, sans-serif;
  line-height: 1.5;
  color: white;
}

.navbar {
  height: 50px;
  position: fixed;
  width: 100%;
  background-image: linear-gradient(#081829 , #6B798C);
  z-index: 100;
}

.wrapper, .main-wrapper {
  width: 1200px;
  margin: 0 auto;
  padding-left: 30px;
  padding-right: 30px;
  box-sizing: border-box;

}

.navbar .wrapper {
  background-color: rgba(255,255,255,0.1);
}

.main-wrapper {
  font-size: 1.1em;
  padding-top: 80px;
  padding-bottom: 80px;
  padding-right: 80px;
  padding-left: 80px;
  background-image:  url("https://i.imgur.com/VGv0QE1.jpg");
  background-size: cover;
  position: relative;
  z-index: 1;
}

.logo {
  display: inline-block;
}

.logo a {
  line-height: 50px;
  font-size: 1.75em;
  font-weight: bold;
  text-decoration: none;
  color: gold;
}

.mainmenu {
  float: right;
  list-style: none;
  padding: 0;
  margin: 0;
  font-size: 0;
}

.mainmenu li {
  display: inline;
}

button{
  line-height: 50px;
  text-decoration: none;
  color: black;
  font-size: 18px;
  font-weight: bold;
  padding: 0;
  border: none;
  background: none;
}

button:hover{
  color: #EDA444;
}

.mainmenu li a{
  line-height: 50px;
  text-decoration: none;
  color: black;
  font-size: 18px;
  font-weight: bold;
}

.mainmenu li a:hover {
  color: #EDA444;
}

.mainmenu li:not(:last-child) {
  margin-right: 30px;
}

img.myface {
  float: left;
  border-radius: 10px;
  margin-right: 30px;
}

.section:before {
  content: " ";
  display: block;
  position: absolute;
  width: 100%;
  height: 100%;
  background-color: rgba(11,66,131,0.5);
  left: 0px;
  top: 0px;
  z-index: -1;
  border-radius: 10px;
}



.section {
  z-index: 100;
  position: relative;
  padding: 30px;
  vertical-align: top;
  
}

.section h1 {
  margin: 0;
}

.section p {
  position: relative;
}

.section a{
  color: gold;
  font-weight: bold;
  text-decoration: none;
}

.section a:hover {
  color: red;
}

img.ninetysdesk {
  border-radius: 10px;
  margin-left: 30px;
  float: right;
}

img.webtech {
  border-radius: 10px;
  margin-right: 30px;
  float: left;
}

img {
  box-shadow: 2px 2px 3px 0px rgba(0,0,0,0.8);
  background-color: white;
}

td {
  padding: 10px;
  vertical-align: bottom;
}

table {
  float: left;
}

.clearfix {
  clear: both;
  height: 0px;
}
</style>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<nav class="navbar">
    <div class="wrapper">
        <div class="logo"><a href="{% url 'lab3:index' %}">Security Lab</a></div>
        <ul class="mainmenu">
          <form method="post">
            {% csrf_token %}
          {% if username != "" %}
          <li><a href="{% url 'lab3:details' %}">Welcome {{username}}</a></li>
          <li><a href="{% url 'lab3:search' %}">Search Users</a></li>
          <button type="submit">Log Out</button>
          {% endif %}
          </form>
          {% if username == "" %}
          <li><a href="{% url 'lab3:login' %}">Login</a></li>
          <li><a href="{% url 'lab3:register' %}">Register</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    
    <div class="main-wrapper">
     <div class="section about-section">
       <h1>Vulnerable Web Application</h1>
       <p>This application contains vulnerabilities. Try to find them.</p>
     </div>
    </div>
    
</html>

templates/login.html

<style>
html {
  background-color: #565656
}

body {
  font-size: 18px;
  font-family: Verdana, Geneva, sans-serif;
  line-height: 1.5;
  color: white;
}

.navbar {
  height: 50px;
  position: fixed;
  width: 100%;
  background-image: linear-gradient(#081829 , #6B798C);
  z-index: 100;
}

.wrapper, .main-wrapper {
  width: 1200px;
  margin: 0 auto;
  padding-left: 30px;
  padding-right: 30px;
  box-sizing: border-box;

}

.navbar .wrapper {
  background-color: rgba(255,255,255,0.1);
}

.main-wrapper {
  font-size: 1.1em;
  padding-top: 80px;
  padding-bottom: 80px;
  padding-right: 80px;
  padding-left: 80px;
  background-image:  url("https://i.imgur.com/VGv0QE1.jpg");
  background-size: cover;
  position: relative;
  z-index: 1;
}

.logo {
  display: inline-block;
}

.logo a {
  line-height: 50px;
  font-size: 1.75em;
  font-weight: bold;
  text-decoration: none;
  color: gold;
}

.mainmenu {
  float: right;
  list-style: none;
  padding: 0;
  margin: 0;
  font-size: 0;
}

.mainmenu li {
  display: inline;
}

.mainmenu li a {
  line-height: 50px;
  text-decoration: none;
  color: black;
  font-size: 18px;
  font-weight: bold;
}

.mainmenu li a:hover {
  color: #EDA444;
}

.mainmenu li:not(:last-child) {
  margin-right: 30px;
}

img.myface {
  float: left;
  border-radius: 10px;
  margin-right: 30px;
}

.section:before {
  content: " ";
  display: block;
  position: absolute;
  width: 100%;
  height: 100%;
  background-color: rgba(11,66,131,0.5);
  left: 0px;
  top: 0px;
  z-index: -1;
  border-radius: 10px;
}



.section {
  z-index: 100;
  position: relative;
  padding: 30px;
  vertical-align: top;
  
}

.section h1 {
  margin: 0;
}

.section p {
  position: relative;
}

.section a{
  color: gold;
  font-weight: bold;
  text-decoration: none;
}

.section a:hover {
  color: red;
}

img.ninetysdesk {
  border-radius: 10px;
  margin-left: 30px;
  float: right;
}

img.webtech {
  border-radius: 10px;
  margin-right: 30px;
  float: left;
}

img {
  box-shadow: 2px 2px 3px 0px rgba(0,0,0,0.8);
  background-color: white;
}

td {
  padding: 10px;
  vertical-align: bottom;
}

table {
  float: left;
}

.clearfix {
  clear: both;
  height: 0px;
}
</style>
<html>

<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/aes.js"></script>
<script>
  function encrypt() {
      var hash = CryptoJS.MD5(document.getElementById("password").value);
      document.getElementById("password").value = hash;
  }
</script>


<meta name="viewport" content="width=device-width, initial-scale=1">
<nav class="navbar">
    <div class="wrapper">
      <div class="logo"><a href="{% url 'lab3:index' %}">Security Lab</a></div>
      <ul class="mainmenu">
        </ul>
      </div>
    </nav>
    {% if message != None %}
    <script>alert("{{message}}")</script>
    {% endif %}
    <div class="main-wrapper">
     <div class="section about-section">
      <h1>Enter your credentials!</h1>
      <div class="login-form">
        <form method="post">
          {% csrf_token %}
          <!-- username:admin,password:admin -->
          <input type="text" name="user" placeholder="Username"/>
          <input id="password" type="password" name="pass" placeholder="Password" />
          <button type="submit"  onclick="encrypt()">Submit</button>
        </form>
      </div>
     </div>
    </div>
</html>

templates/search.html

<style>
    html {
      background-color: #565656
    }
    
    body {
      font-size: 18px;
      font-family: Verdana, Geneva, sans-serif;
      line-height: 1.5;
      color: white;
    }
    
    .navbar {
      height: 50px;
      position: fixed;
      width: 100%;
      background-image: linear-gradient(#081829 , #6B798C);
      z-index: 100;
    }
    
    .wrapper, .main-wrapper {
      width: 1200px;
      margin: 0 auto;
      padding-left: 30px;
      padding-right: 30px;
      box-sizing: border-box;
    
    }
    
    .navbar .wrapper {
      background-color: rgba(255,255,255,0.1);
    }
    
    .main-wrapper {
      font-size: 1.1em;
      padding-top: 80px;
      padding-bottom: 80px;
      padding-right: 80px;
      padding-left: 80px;
      background-image:  url("https://i.imgur.com/VGv0QE1.jpg");
      background-size: cover;
      position: relative;
      z-index: 1;
    }
    
    .logo {
      display: inline-block;
    }
    
    .logo a {
      line-height: 50px;
      font-size: 1.75em;
      font-weight: bold;
      text-decoration: none;
      color: gold;
    }
    
    .mainmenu {
      float: right;
      list-style: none;
      padding: 0;
      margin: 0;
      font-size: 0;
    }
    
    .mainmenu li {
      display: inline;
    }
    
    button{
      line-height: 50px;
      text-decoration: none;
      color: black;
      font-size: 18px;
      font-weight: bold;
      padding: 0;
      border: none;
      background: none;
    }
    
    button:hover{
      color: #EDA444;
    }
    
    .mainmenu li a{
      line-height: 50px;
      text-decoration: none;
      color: black;
      font-size: 18px;
      font-weight: bold;
    }
    
    .mainmenu li a:hover {
      color: #EDA444;
    }
    
    .mainmenu li:not(:last-child) {
      margin-right: 30px;
    }
    
    img.myface {
      float: left;
      border-radius: 10px;
      margin-right: 30px;
    }
    
    .section:before {
      content: " ";
      display: block;
      position: absolute;
      width: 100%;
      height: 100%;
      background-color: rgba(11,66,131,0.5);
      left: 0px;
      top: 0px;
      z-index: -1;
      border-radius: 10px;
    }
    
    
    
    .section {
      z-index: 100;
      position: relative;
      padding: 30px;
      vertical-align: top;
      
    }
    
    .section h1 {
      margin: 0;
    }
    
    .section p {
      position: relative;
    }
    
    .section a{
      color: gold;
      font-weight: bold;
      text-decoration: none;
    }
    
    .section a:hover {
      color: red;
    }
    
    img.ninetysdesk {
      border-radius: 10px;
      margin-left: 30px;
      float: right;
    }
    
    img.webtech {
      border-radius: 10px;
      margin-right: 30px;
      float: left;
    }
    
    img {
      box-shadow: 2px 2px 3px 0px rgba(0,0,0,0.8);
      background-color: white;
    }
    
    td {
      padding: 10px;
      vertical-align: bottom;
    }
    
    .clearfix {
      clear: both;
      height: 0px;
    }
    </style>
    <html>
    {% autoescape off %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <nav class="navbar">
        <div class="wrapper">
            <div class="logo"><a href="{% url 'lab3:index' %}">Security Lab</a></div>
            <ul class="mainmenu">
              <form method="post">
                {% csrf_token %}
              {% if username != "" %}
              <li><a href="{% url 'lab3:details' %}">Welcome {{username}}</a></li>
              <li><a href="{% url 'lab3:search' %}">Search Users</a></li>
              <button type="submit">Log Out</button>
              {% endif %}
              </form>
              {% if username == "" %}
              <li><a href="{% url 'lab3:login' %}">Login</a></li>
              {% endif %}
            </ul>
          </div>
        </nav>
        
        <div class="main-wrapper">
         <div class="section about-section">
            <center><h1>Enter username to search for</h1></center>
            {% if searched != "" %}
            <h2>You've searched for {{searched}}</h2>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <input id="usersearch" name="usersearch"/>
                <button type="submit">Search</button>            
            </form>
                    <table>
            <thead>
            <tr>
                <th>Available Users</th>
            </tr>
            </thead>
            <tbody>
                <td>
                    {% for user in users %}
                    <tr>
                        <td>{{user}}</td>
                    </tr>
                    {% endfor %}
                </td>
            </tbody>
        </table>
         </div>
        </div>
        {% endautoescape %}

    </html>